# Generated by Django 4.0.2 on 2022-02-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shoe_address',
            new_name='shop_address',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shoe_name',
            new_name='shop_name',
        ),
    ]
